In [1]:
from tranform import get_plane_equation
import numpy as np
import pickle
import pyransac3d
RESOLUTION = 0.005
with open('map-20220122-155134.pkl', 'rb') as f:
    data = pickle.load(f)

data = np.array(data)
plane = pyransac3d.Plane()

coeffs_stack = np.zeros((data.shape[0],4))

for i in range(data.shape[0]):
    height_map = data[i]
    coeffs = get_plane_equation(plane, height_map, RESOLUTION)
    #print(coeffs)
    coeffs_stack[i] = coeffs

mean_coeffs = np.mean(coeffs_stack, axis=0)




In [13]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.5f}".format(x)})
mean_coeffs

array([0.03321, -0.91444, -0.40327, 0.70297])

In [14]:
np.max(coeffs_stack - mean_coeffs)
np.max(np.abs(coeffs_stack - mean_coeffs), axis=0)
np.var((coeffs_stack - mean_coeffs), axis=0)

array([0.00004, 0.00001, 0.00002, 0.00002])

In [4]:
coeffs_stack

array([[0.041, -0.915, -0.401, 0.694],
       [0.031, -0.913, -0.407, 0.701],
       [0.033, -0.911, -0.412, 0.705],
       [0.039, -0.911, -0.410, 0.704],
       [0.035, -0.915, -0.402, 0.702],
       [0.036, -0.914, -0.405, 0.703],
       [0.034, -0.914, -0.404, 0.703],
       [0.030, -0.914, -0.404, 0.706],
       [0.035, -0.914, -0.403, 0.702],
       [0.035, -0.915, -0.402, 0.700],
       [0.046, -0.914, -0.404, 0.698],
       [0.028, -0.914, -0.405, 0.706],
       [0.048, -0.912, -0.408, 0.698],
       [0.034, -0.913, -0.406, 0.702],
       [0.041, -0.911, -0.411, 0.706],
       [0.034, -0.916, -0.400, 0.703],
       [0.024, -0.916, -0.401, 0.708],
       [0.028, -0.917, -0.399, 0.703],
       [0.036, -0.915, -0.403, 0.703],
       [0.032, -0.916, -0.399, 0.703],
       [0.030, -0.921, -0.389, 0.696],
       [0.027, -0.918, -0.396, 0.701],
       [0.028, -0.918, -0.396, 0.694],
       [0.040, -0.916, -0.399, 0.694],
       [0.016, -0.918, -0.396, 0.707],
       [0.035, -0.913, -0